Gen 4 - Change Weather via Script
kingdom-of-ds-hacking/kingdom-of-ds-hacking.github.io pull request #10
Opened 2022-09-04 18:20 UTC by BluRosie

# Name of Resource
gen 4 change weather via script

# Description
gen 4 doesn't natively come with the ability to change weather in a script.  there are a few script commands in each, however, that set everything to a specific weather.  we can modify these at runtime to induce a change to a separate weather

# Which Generation (4/5/Universal)?
gen 4 (pt/hgss)

# Notes
short and sweet

2022-09-10 15:13 UTC, PlatinumMaster requested changes
Came to resolve some PRs.

2022-09-10 15:13 UTC, PlatinumMaster commented on src/SUMMARY.md
> +        - [Setting the Weather from a Script<sup>*Platinum/HGSS*</sup>](gen4/universal/guides/script_weather.md)
Nice touch. Perhaps this could be a badge or something similar, so it can be easily visible. Not sure if mdBook supports it, though.

Perhaps we could try something like this so it looks a bit cleaner:
Setting the Weather from a Script <sup>(*Platinum/HGSS*)</sup>

2022-09-10 15:13 UTC, PlatinumMaster commented on src/gen4/universal/guides/script_weather.md
> +# Script Weather <sup>*Platinum/HGSS*</sup>
Similar to above: title should probably be similar to this, so it looks a bit better:
Setting the Weather from a Script <sup>(*Platinum/HGSS*)</sup>

2022-09-10 15:13 UTC, PlatinumMaster commented on src/gen4/universal/guides/script_weather.md
> +The precise value may **NOT** work if you've messed with the length of the arm9. To find it in a modified game/other language version, the strip of bytes is as follows:
Maybe this should be merged with the previous section before the tutorial starts. There is a href to this section, however    it might be best to just have it in a continuous order for clarity sake (and, to minimize the possibilities of someone skimming over an important section).

2022-09-12 13:53 UTC, BluRosie commented on src/SUMMARY.md
> +        - [Setting the Weather from a Script<sup>*Platinum/HGSS*</sup>](gen4/universal/guides/script_weather.md)
I'd imagine that if it were just an image, we could totally just put one there

2022-09-12 14:01 UTC, BluRosie commented
Will be squashing those when I get to a git client

2022-09-13 02:58 UTC, PlatinumMaster approved these changes

2022-09-13 02:58 UTC, merged